# Generated by Django 4.0.3 on 2022-04-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_staticimages_alter_project_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticImages',
            new_name='StaticImage',
        ),
    ]
